env:
  - GHCVER=7.0.4
  - GHCVER=7.4.1
  - GHCVER=7.4.2
  - GHCVER=7.6.3
  - GHCVER=7.8.2
before_install:
  - sudo add-apt-repository -y ppa:hvr/ghc
  - sudo apt-get update -qq
  - sudo apt-get --no-install-recommends install libgtksourceview-3.0-dev alex happy
  - sudo apt-get install cabal-install-1.18 ghc-$GHCVER
  - export CABAL=cabal-1.18
  - export PATH=$HOME/.cabal/bin:/opt/ghc/$GHCVER/bin:$PATH
  - $CABAL update
  - |
    if [ $GHCVER = "head" ] || [ $GHCVER = "7.8.2" ]; then
      $CABAL install happy alex
    fi
  - $CABAL install Cabal
install:
  - $CABAL install gtk2hs-buildtools
script:
  - $CABAL install
notifications:
  irc:
    channels: "irc.freenode.net#leksah"
  email: true
